!!python/object:argparse.Namespace
add_model_for_coverage: true
addcovloss: false
addkmerloss: false
addvars: true
batch_size: 1024
contig_len: 1000
cov_meannormalize: false
cov_minmaxnormalize: false
cov_standardization: false
covmodel_notl2normalize: false
covmodel_temperature: 0.1
covmodelepochs: 50
data: /vol/data/benchmark/runs/baseline_rerun/comebin_out/data_augmentation
device: !!python/object/apply:torch.device
- cpu
dropout_value: 0.2
earlystop: true
emb_szs: 2048
emb_szs_forcov: 2048
epochs: 200
finetunelr_ratio: 0.1
finetunepretrainmodel: false
fp16_precision: false
kmerMetric_notl2normalize: false
kmer_l2_normalize: false
kmer_model_path: empty
kmermodel_temperature: 0.1
lambdakmerloss2: 1
lambdaloss2: 1
log_every_n_steps: 20
lossbalance: false
lr: 0.001
n_layer: 3
n_layer_forcov: 3
n_views: 6
nokmer: false
not_load_kmermetric_state: false
notuse_scheduler: false
notuseaug0: false
num_threads: 32
out_dim: 128
out_dim_forcov: 128
output_path: /vol/data/benchmark/runs/baseline_rerun/comebin_out/comebin_res
pretrain_coveragemodel: false
pretrain_kmer_model_path: 'no'
subcmd: train
temperature: 0.15
vars_sqrt: true
weight_decay: 0.0001
workers: 5
