!!python/object:argparse.Namespace
addvars: true
batch_size: 1024
contig_len: 1000
cov_meannormalize: false
cov_minmaxnormalize: false
cov_standardization: false
data: /vol/data/benchmark/runs/cami3_v11_20260926_rerun/comebin_out/data_augmentation
device: !!python/object/apply:torch.device
- cpu
dropout_value: 0.2
earlystop: true
emb_szs: 2048
emb_szs_forcov: 2048
epochs: 200
fp16_precision: false
log_every_n_steps: 20
lr: 0.001
n_layer: 3
n_layer_forcov: 3
n_views: 6
notuse_scheduler: false
notuseaug0: false
num_threads: 32
out_dim: 128
out_dim_forcov: 128
output_path: /vol/data/benchmark/runs/cami3_v11_20260926_rerun/comebin_out/comebin_res
seed: 42
subcmd: train
temperature: 0.07
vars_sqrt: true
weight_decay: 0.0001
